# Compile the Rcpp code with C++ implementation files
library(Rcpp)

# Set the working directory to the project root
# This is necessary to ensure the include paths are correct
setwd("/Users/mark/Documents/Cline/bartMachine_port")

# Create a package directory structure
pkg_dir <- file.path(tempdir(), "bartMachine")
dir.create(pkg_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(pkg_dir, "src"), showWarnings = FALSE)
dir.create(file.path(pkg_dir, "R"), showWarnings = FALSE)
dir.create(file.path(pkg_dir, "man"), showWarnings = FALSE)

# Copy all C++ files to the package src directory
cpp_files <- list.files("src/cpp", pattern = "\\.cpp$", full.names = TRUE)
for (file in cpp_files) {
  file.copy(file, file.path(pkg_dir, "src", basename(file)), overwrite = TRUE)
}

# Copy all header files to the package src directory
header_files <- list.files("src/cpp/include", pattern = "\\.h$", full.names = TRUE)
for (file in header_files) {
  file.copy(file, file.path(pkg_dir, "src", basename(file)), overwrite = TRUE)
}

# Copy the Rcpp interface file to the package src directory
file.copy("src/rcpp/bartmachine_rcpp.cpp", file.path(pkg_dir, "src", "bartmachine_rcpp.cpp"), overwrite = TRUE)

# Copy the R files to the package R directory
file.copy("src/r/bartmachine_rcpp.R", file.path(pkg_dir, "R", "bartmachine_rcpp.R"), overwrite = TRUE)

# Create a DESCRIPTION file
writeLines(
  c(
    "Package: bartMachine",
    "Type: Package",
    "Title: Bayesian Additive Regression Trees",
    "Version: 2.0.0",
    "Date: 2025-06-06",
    "Authors@R: c(",
    "    person(\"Adam\", \"Kapelner\", email = \"kapelner@qc.cuny.edu\", role = c(\"aut\", \"cre\")),",
    "    person(\"Justin\", \"Bleich\", email = \"jbleich@wharton.upenn.edu\", role = \"aut\"),",
    "    person(\"Gannon\", \"Mark\", email = \"mark.a.gannon@gmail.com\", role = \"aut\"),",
    "    person(\"C++ Port Team\", role = \"aut\")",
    "  )",
    "Description: An advanced implementation of Bayesian Additive Regression Trees (BART) with expanded features for data analysis and visualization. This version uses a C++ backend instead of the original Java implementation.",
    "License: GPL-3",
    "Depends:",
    "    R (>= 3.5.0)",
    "Imports:",
    "    Rcpp (>= 1.0.0),",
    "    graphics,",
    "    stats,",
    "    utils",
    "LinkingTo: Rcpp",
    "RoxygenNote: 7.2.3",
    "Encoding: UTF-8"
  ),
  file.path(pkg_dir, "DESCRIPTION")
)

# Create a NAMESPACE file
writeLines(
  c(
    "# Generated by roxygen2: do not edit by hand",
    "",
    "# Export all functions",
    "export(set_seed)",
    "export(rand)",
    "export(sample_from_norm_dist)",
    "export(sample_from_inv_gamma)",
    "export(bartmachine_regression)",
    "export(bartmachine_classification)",
    "",
    "# S3 methods",
    "S3method(predict, bartmachine_regression)",
    "S3method(predict, bartmachine_classification)",
    "S3method(print, bartmachine_regression)",
    "S3method(print, bartmachine_classification)",
    "S3method(get_variable_importance, bartmachine_regression)",
    "S3method(get_variable_importance, bartmachine_classification)",
    "",
    "# Import Rcpp",
    "importFrom(Rcpp, sourceCpp)",
    "",
    "# Use dynamic library",
    "useDynLib(bartMachine, .registration = TRUE)"
  ),
  file.path(pkg_dir, "NAMESPACE")
)

# Create a Makevars file to ensure proper compilation
writeLines(
  c(
    "PKG_CPPFLAGS = -I../inst/include",
    "PKG_CXXFLAGS = $(CXX11STD) -O3",
    "CXX_STD = CXX11"
  ),
  file.path(pkg_dir, "src", "Makevars")
)

# Build the package
cat("Building the package...\n")
install.packages(pkg_dir, repos = NULL, type = "source")

# Print success message
cat("Package built and installed successfully!\n")
cat("You can now use the bartMachine package in R.\n")
